### ISSUE TITLE
.rcwa converter to .rcw

### ISSUE THREAD

**Issue by Gordon9999** [wootguy/rcbot#2]
how about to make a converter from .RCWA to .RCW? Like Cheeseh's .RCW to .RCWA one. It's will be helpful for waypointers since the most waypoints of old rcbots are outdated.

**Comment by wootguy** [comment]
Good idea. Reversing the process should be easy if a converter was already made for one direction, but it looks like the converter source is private.

**Comment by wootguy** [comment]
It was easy even without the source. A tool is included in the release zip now.
https://github.com/wootguy/rcbot/releases/download/sc525/rcbot_sc525.zip

**Comment by Gordon9999** [comment]
I tested the converter and discovered an issue - .rcws become completely non-functional and useless, there aren't any waypoints on map

**Comment by wootguy** [comment]
can you attach/link an .rcwa that failed to convert? I tested with this one from the [RCBot5](https://github.com/rcbotCheeseh/RCBotSven5/tree/master) github and it worked.
[4ways.zip](https://github.com/wootguy/rcbot/files/12926212/4ways.zip)

**Comment by Gordon9999** [comment]
well, it's my custom waypoints
[sc_tropical1_final.zip](https://github.com/wootguy/rcbot/files/12937765/sc_tropical1_final.zip)
I think the issue is that these waypoints include types that old RCBots don't have.

**Comment by wootguy** [comment]
The problem is the map name is missing from that file. I updated the converter to use the file name as the map name as a fallback The name is case sensitive so check that .rcwa name matches the map name exactly if this happens again. Updated tool here:
https://github.com/wootguy/rcbot/releases/download/sc525/rcbot_sc525.zip

**Comment by Gordon9999** [comment]
nah, still doesn't work
![image](https://github.com/wootguy/rcbot/assets/24679760/95832921-27fc-48f0-a771-dfcbbdbf1dc0)
the problem here's that instead of the file name, the entire directory is written

**Comment by wootguy** [comment]
Attempt #3
https://github.com/wootguy/rcbot/releases/download/sc525/rcbot_sc525.zip

**Comment by Gordon9999** [comment]
doesn't work
no file name again

**Comment by wootguy** [comment]
What command are you running? Idk what's wrong now.

**Comment by Gordon9999** [comment]
finally works! thank you, w00tguy! you're really cool

**Comment by danylopez123** [comment]
Sorry for bumping a close issue but, what about the .ini files from the .rcwa files?
Those are the specific objective files and i dont know how the previous ported RCBot will handle that.

**Comment by wootguy** [comment]
Objective scripting doesn't exist in the metamod rcbot. There is only the objective waypoint flag.
