### ISSUE TITLE
Bots are trying to destroy friendly breakables

### ISSUE THREAD

**Issue by Gvbavx** [wootguy/rcbot#3]
![20231021095540_1](https://github.com/wootguy/rcbot/assets/145967852/3e95b99d-4ecd-487e-b5ad-68f0a11c8df3)
![20231021095713_1](https://github.com/wootguy/rcbot/assets/145967852/4bbf9aef-56e0-490c-b9ba-240c95e67b5a)
It seems that those bots don't know if a breakable is friendly

**Comment by wootguy** [comment]
There was a config setting called `sc_breakable_classes_ally` but I guess that was part of the SC4.8 build. I updated the bot to ignore allied breakables instead. It works on quarter and defendthefort at least.
https://github.com/wootguy/rcbot/releases/download/sc525/rcbot_sc525.zip
