### ISSUE TITLE
Bots won't destroy turrets

### ISSUE THREAD

**Issue by Gvbavx** [wootguy/rcbot#4]
![20231021222943_1](https://github.com/wootguy/rcbot/assets/145967852/109576b0-173c-4ee2-b646-cfb9ba99453e)
![20231021225124_1](https://github.com/wootguy/rcbot/assets/145967852/f1de2ebc-01a1-401f-bf5a-be04d6ea66de)
![20231021225128_1](https://github.com/wootguy/rcbot/assets/145967852/561dd966-da64-4f06-b3f6-4c3b77774918)
![20231021225631_1](https://github.com/wootguy/rcbot/assets/145967852/42928b40-eb49-42a5-8ad5-e2ac995a5d3d)
The bots won't attack turrets but they will attack mini turrets?

**Comment by wootguy** [comment]
https://github.com/wootguy/rcbot/releases/download/sc525/rcbot_sc525.zip

**Comment by Gvbavx** [comment]
It worked! Thank you for solving the problem!
