### ISSUE TITLE
bots refuse shooting through Akimbo UZIs

### ISSUE THREAD

**Issue by Gordon9999** [wootguy/rcbot#8]
bots just stand with them, but they refuse to shoot. with one uzi they can shoot.

**Comment by Gordon9999** [comment]
ok, it's happens sometimes, or I just stupid, idk

**Comment by Gordon9999** [comment]
nope, I tested this again, they really don't know how to use this
![image](https://github.com/wootguy/rcbot/assets/24679760/83689754-4f72-42a5-85f6-049eb7b10fb3)

**Comment by Gordon9999** [comment]
I think I understand why this happens occasionally. The bots probably think that when they pick up the second uzi, it's still the same "weapon_uzi" and they continue shooting. But when they are given the "weapon_akimbouzi", it's something unfamiliar to them, resulting in the behavior I described earlier.

**Comment by wootguy** [comment]
The akimbo uzi and normal uzi were merged into the same weapon for sven 5.0. That confused them. bot_weapons.ini was updated in addition to the .dll.
https://github.com/wootguy/rcbot/releases/download/sc525/rcbot_sc525.zip
