### ISSUE TITLE
Bots keep targeting func_button or func_breakable

### ISSUE THREAD

**Issue by Gvbavx** [wootguy/rcbot#9]
Videos:
Map:sc_tetris1 https://github.com/wootguy/rcbot/assets/145967852/b16d0cb9-4482-49bf-851e-b1d0e98cfb02
Map:sc_dark_seekers_final https://github.com/wootguy/rcbot/assets/145967852/fc2b223d-42ae-48ba-875f-d9d014618e1b
Somehow bots keep shooting the wall

Pictures:
![20231024211056_1](https://github.com/wootguy/rcbot/assets/145967852/b663fc56-d8ae-4e54-bb87-2685687bac4a)
![20231024211137_1](https://github.com/wootguy/rcbot/assets/145967852/66e6c52c-e3d0-4400-8771-219c5ddfcb60)
Their target is func_button or func_breakable but there was no func_button or func_breakable in sight

**Comment by wootguy** [comment]
in sc_tetris1 there is a button here. They need to shoot it for the elevator. They don't understand how the entities are connected so they just always shoot it, just like how they always press buttons.
![image](https://github.com/wootguy/rcbot/assets/12087544/a206cdd3-a2cb-4267-9ca9-e2005bc9b26b)

in sc_dark_seekers_final they're trying to break the glass on the street lights. They're not great shots though, and are maybe using the shotgun from too far away.
![image](https://github.com/wootguy/rcbot/assets/12087544/89e9ed35-178f-4023-93ea-a3188f9729ed)
